apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL for Let's Encrypt's staging environment.
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: yashpal2104@example.com # IMPORTANT: Change this to your email address
    privateKeySecretRef:
      # This Secret will be created to store your ACME account's private key.
      name: letsencrypt-staging-private-key
    solvers:
    # This tells cert-manager how to prove you own the domain.
    # The http01 solver is the easiest for this setup.
    - http01:
        ingress:
          class: nginx
